### ISSUE TITLE
Getting 0% in total coverage

### ISSUE THREAD

**Issue by ArcherEmiya05** [gmazzo/gradle-android-test-aggregation-plugin#118]
Below is a submodule residing in `lib` directory of app module and it is very small, but its seems in total coverage it is not being included. Is this some formatting issue for the total calculated coverage or the side effect of doing code coverage in a multi-module project? It's small but still, the coverage should not be 0%.

<img width="928" alt="image" src="https://github.com/gmazzo/gradle-android-test-aggregation-plugin/assets/38008900/5230335e-309b-4b54-ab6b-d2f778211d14">
<img width="1369" alt="image" src="https://github.com/gmazzo/gradle-android-test-aggregation-plugin/assets/38008900/74863cfd-a7a3-440f-937c-bdf719d789d1">

Also, generated DAOs from Room is not being detected despite covering. This is not the same report when I use the actual JaCoCo plugin in a single module project. I tried adding `enableAndroidTestCoverage` but getting `Execution failed for task ':jacocoAggregatedReport'.`. I know there is an ongoing feature request for instrumented test, is this issue related to that current limitation of this plugin or I am running a wrong command? Thanks

**Comment by gmazzo** [comment]
Hi @ArcherEmiya05, can you provide a minimal project where the issues you are mentioning can be easily reproduced?

I won't be able to research them otherwise

**Comment by ArcherEmiya05** [comment]
Will try it but I am currently have plenty on my plate now so I probably won't be able to submit one anytime soon. However is it possible that this can happen due to misconfiguration? I did not add jacoco plugins on those android libraries I listed using `include` since if my understanding is correct, it is only needed for plain Kotlin module where you need to add JVM plugin as well.
