### ISSUE TITLE
Adding --continue for testAggregatedReport

### ISSUE THREAD

**Issue by ArcherEmiya05** [gmazzo/gradle-android-test-aggregation-plugin#119]
I think adding an option to continue the tests execution despite having failed test would be great. This is similar to the late `android-reporting` for multi-module.

**Comment by gmazzo** [comment]
`--continue` is flag from Gradle and not from any specific plugin and allows all noon dependent tasks to run even if another from another branch in the task graph has failed.

So unless a misunderstood the request, this is supported already.
