### ISSUE TITLE
Can we change the directory for tests result? 

### ISSUE THREAD

**Issue by ArcherEmiya05** [gmazzo/gradle-android-test-aggregation-plugin#120]
Hi, I am not too familiar with JaCoCo  thus I do not know if this feature is already available and just share similar behavior with a typical JaCoCo setup for Android. Can we change the generated HTML and XML report of tests?

**Comment by gmazzo** [comment]
As it's stated in the project README.md, this project builds upon the official JaCoCo Report Aggregation Plugin and Test Report Aggregation Plugin.

I'd suggest you to first read their documentation (or search online) which is very complete. Changing the directory for individual reports is provided and documented by Gradle.

I'd like to avoid the project to get polluted with support tickets, as issues are meant to report problems or new functionally.

**Comment by ArcherEmiya05** [comment]
I tried to check for reference but I don't think it is the same when using this library?
https://discuss.gradle.org/t/how-to-change-test-result-directory-when-using-test-report-aggregation-plugin/48132

Is this not supported?

**Comment by gmazzo** [comment]
It is, you just need a basic Gradle understanding.

For instance, in KTS, you can change the base dir for all kind of reports to `"$projectDir/reports"` by doing:
```kotlin
reporting.baseDir = layout.projectDirectory.dir("reports").asFile
```

**Comment by ArcherEmiya05** [comment]
Thanks, I was able to change the directory with the below code.

```
tasks.testAggregatedReport {
    destinationDirectory.set(file("$rootDir/build/unitTest-results"))
}
```
