### ISSUE TITLE
Exclude option

### ISSUE THREAD

**Issue by Fabi755** [gmazzo/gradle-android-test-aggregation-plugin#13]
Thank you for this awesome plugin. It works like a charm! 💙 🖤 💜

I wondering if can add an exclude filter option for add patterns to keep some generated stuff away.

I don't found something in your example. Additional I already tried a lot of things without success. I'm not sure if this plugin does not supporting this or my missing experience with JaCoCo are the problem.

Thanks in advance!

**Comment by gmazzo** [comment]
Implemented on `1.1.0`

**Comment by Fabi755** [comment]
Wow! Very fast response and feature creation 😮

I have build in this now, and it works all as expected. Thank you!
