### ISSUE TITLE
[ASK]How to run integrate with AffectedModuleDetector

### ISSUE THREAD

**Issue by jboxx** [gmazzo/gradle-android-test-aggregation-plugin#161]
Hi thanks for making this plugin,

want to ask, is it possible to override jacocoAggregation task to run runAffectedUnitTests so it will not run all of modules and buildTypes?

**Comment by gmazzo** [comment]
I'm not sure how `AffectedModuleDetector` works, but if it relies on forcing the skip of some test tasks based on GIT diff or similar approaches, I'd state it's a hacky approach.

You should always configure all your modules, and rely on Gradle's `Build Cache` instead. The UP-TO-DATE logic will do the magic at task level, including `Test`s tasks.
