### ISSUE TITLE
Build fails with plugin exception when having a dedicated test module

### ISSUE THREAD

**Issue by shining-cat** [gmazzo/gradle-android-test-aggregation-plugin#32]
Hi,
I'm really happy and grateful to see this made into a gradle plugin, so first of all, a huge thank you, and congrats!
I have extracted my instrumented tests from my `app` module to a dedicated module as per:
https://developer.android.com/studio/test/advanced-test-setup#use-separate-test-modules-for-instrumented-tests
and
https://proandroiddev.com/effective-testing-with-android-test-only-modules-3164ed9b20a0
So this new module is a `com.android.test`, not a `library` or app `module`. It contains all the test classes in the main folder instead of the androidTests folder.
My tests are covering the data module I also have separated from the others, as a `library` module. (For some reason, I never could run the instrumented tests in a `library` module, when they run fine in the `app` module, or a `test` module, but that is off-topic.)
Prior to this move, the plugin I applied from the project build.gradle was working fine (albeit not including the instrumented tests, but I seem to have understood that this is expected for now).
Now my build fails with the exception : 
`An exception occurred applying plugin request [id: 'com.android.test']
> Failed to apply plugin class 'io.github.gmazzo.android.test.aggregation.AndroidTestCoverageAggregationPlugin'.
   > Extension of type 'TestedExtension' does not exist. Currently registered extension types: [ExtraPropertiesExtension, BasePluginExtension, DefaultArtifactPublicationSet, SourceSetContainer, ReportingExtension, JavaToolchainService, JavaPluginExtension, TestExtension, TestAndroidComponentsExtension, NamedDomainObjectContainer<BaseVariantOutput>]
`

below is the full stacktrace
[build-fail.txt](https://github.com/gmazzo/gradle-android-test-aggregation-plugin/files/11636095/build-fail.txt)

**Comment by gmazzo** [comment]
Thankyou for reporting this! Fixed at `1.1.1`

**Comment by shining-cat** [comment]
Thank you for acting so fast!

FWIW, I needed to exclude the test module from the plugin task with: 
`testAggregation {
    modules {
        exclude(project(":dataInstrumentedTests"))
    }
}`
(the other way of explicitely including all the other modules instead produces the same result, I guess this is up to individual preferences)
Because it was causing an error.
Since I only intend to extract dedicated test modules to run instrumented tests and these are not included in the coverage report anyway, it is no issue to me, but I think it might be worth mentionning so here goes.
[log.txt](https://github.com/gmazzo/gradle-android-test-aggregation-plugin/files/11645296/log.txt)

**Comment by gmazzo** [comment]
Definitely an issue, but I couldn't reproduce in the `ui-tests` demo project I've added on the project. Is possible there you have something else in the setup? Would you be able to share a minimum sample project that triggers the issue?

What I found is that your `dataInstrumentedTests` module exposes `debugTestedApks` conflicting with the `codeCoverageSources` ones. But on mine, that outgoing variant does not exist 🤔

**Comment by shining-cat** [comment]
Mmh... I'll check the difference with your implementation then.
From the top of my mind, it might be tied to the fact I had to specify the app module as the target of the tests module, as this is the only way to get the instrumented tests to run out of the app module I have found...

**Comment by shining-cat** [comment]
I could build a reduced project to share, but that since that would take some time, what would you think about checking the real thing? I can perfectly open you my repo, as it's a personal project. Of course it's a WIP, but I promise it's tidy :)
