### ISSUE TITLE
Groovy DSL Support

### ISSUE THREAD

**Issue by MatthewTPage** [gmazzo/gradle-android-test-aggregation-plugin#37]
It doesn't seem to me that the plugin currently supports the groovy DSl, particularly as it relates to the product flavors DSL.

If it's not supported, it'd be great to add support.

If it is supported, it'd be great to add an example either in the sample project or the README.

**Comment by gmazzo** [comment]
Hi @MatthewTPage the plugin uses a standard Gradle domain object, which should be compatible with both DSL languages. Can you provide more details about the issue itself, or give a sample repo where it happens?

**Comment by gmazzo** [comment]
I'm going to assume you manage to get it work, feel free to reopen it if you have further details to add

**Comment by MatthewTPage** [comment]
Hi @gmazzo! Sorry for the delay. I realized the issue was not related to the DSL language after looking more into it, thanks for your help on that part :)

I've been trying to narrow down why I'm seeing the issue I'm seeing, if I'm able to reproduce in a sample project and still not solve it on my end, I'll post a new issue.

**Comment by gmazzo** [comment]
If you confirm there is an issue here, just comment I'll reopen the issue and take a look at it.
