### ISSUE TITLE
Repository doesn't have a license

### ISSUE THREAD

**Issue by simtel12** [gmazzo/gradle-android-test-aggregation-plugin#4]
Hi,

I found your repository via your [medium post](https://medium.com/@gmazzo65/generating-android-jvm-aggregated-coverage-reports-53e912b2e63c).  I just wanted to mention that per [Github's guidance](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository), you need to specify a license or the default copyright laws apply - preventing anyone from reproducing, distributing, or creating derivative works from your work.

So if you intend this to be open source - or let people use it for much, then you might want to choose a license to use.

If you don't want that kind of usage, the feel free to ignore/close this issue!  :)

**Comment by gmazzo** [comment]
Hi there! I'm going to add a LICENCE.

Menwhile, I'll like to let you know that I finally decided to publish this as a couple of plugins:
[io.github.gmazzo.test.aggregation.coverage](https://plugins.gradle.org/plugin/io.github.gmazzo.test.aggregation.coverage) and
[io.github.gmazzo.test.aggregation.results](https://plugins.gradle.org/plugin/io.github.gmazzo.test.aggregation.results)

**Comment by simtel12** [comment]
Great, thanks!
