### ISSUE TITLE
Could you give me information about supported Android OS, AGP, Java... version

### ISSUE THREAD

**Issue by trietbui85** [gmazzo/gradle-android-test-aggregation-plugin#41]
Hi @gmazzo , could you update the ReadMe to include these info:
```
- What's the supported version of:
+ Android Gradle plugin
+ Java version
+ Gradle Wrapper version
+ ... and so on.
```

**Comment by gmazzo** [comment]
Hi @trietbui85, As I have automated bumps of those libraries, let me think about this in a way that will be automated as well. 

Can you detail your use case for this request? I was expecting as best practice to that projects keep its dependencies updated.

**Comment by gmazzo** [comment]
Closing the issue, since I didn't hear back from you
