### ISSUE TITLE
Error applying plugin

### ISSUE THREAD

**Issue by erawhctim** [gmazzo/gradle-android-test-aggregation-plugin#45]
I feel like I'm missing something very obvious.... but I can't even apply the aggregate results plugin without an error. 
What am I missing?

My root `build.gradle` file looks like this: 
```
plugins {
    id "io.github.gmazzo.test.aggregation.results" version "1.1.1" apply false
}
```

My individual module gradle files look like this: 
```
plugins {
    id 'kotlin'
    id "io.github.gmazzo.test.aggregation.results"
}

testAggregation {
    ...
}

dependencies {
    ....
}
```

I get an error immediately from Gradle: 
```
   > Failed to apply plugin 'io.github.gmazzo.test.aggregation.results'.
      > Cannot add a ReportSpec with name 'testAggregateTestReport' as a ReportSpec with that name already exists.
```

This is an Android project using Android Gradle Plugin v7.3.1, Kotlin v1.9.0, and Gradle v7.5

**Comment by gmazzo** [comment]
Hi @erawhctim, can you provide a sample repo showing the issue? 

> `Cannot add a ReportSpec with name 'testAggregateTestReport' as a ReportSpec with that name already exists.`

I'm wondering if something else in your setup is creating a `testAggregateTestReport` report

**Comment by erawhctim** [comment]
yeah, that's what I thought too. I'll keep poking around and see if I can repro in a standalone project. 
I tried disabling most of my other gradle pugins related to tests (JaCoCo, test retry, test logger, that sort of thing) but couldn't trigger anything other than this error message. 

Am I applying the plugin in the right spots, from what you can tell? Declare it @ the root (with `apply false`) + declare in each module like it's listed above?

**Comment by gmazzo** [comment]
>Am I applying the plugin in the right spots, from what you can tell? Declare it @ the root (with apply false) + declare in each module like it's listed above?

I just noted this. The plugin should be applied at root level **only**. That will add the `testAggregateTestReport`. The plugin will automatically detect child modules using either `java` or `android` plugins and hook them into the aggregated repoort

**Comment by erawhctim** [comment]
Reproduced the error in an empty Gradle project here: 
https://github.com/erawhctim/test-aggregation-plugin-error-repro

**Comment by erawhctim** [comment]
> It's designed to work on a root project

I'm confused; is that not what I'm doing in the repro? Applying the plugin to the root `build.gradle` file?
How should it be applied?

**Comment by gmazzo** [comment]
I'm sorry for not being clear. 

The aggregator plugin should be applied at the root project, that's correct.

The issue is that you are also applying the `kotlin` plugin to the root project, making it incompatible.

Is there any reason for doing that? Is your to m root project also a kotlin/jvm module?

I'd suggest you too add `apply false` to the kotlin plugin in the root project and just apply it in the child project that uses it or use a `subprojects` closure instead of the `allprojects`

**Comment by erawhctim** [comment]
ah! I see now. Yeah honestly I'm not sure if that was intentional, we definitely could use `apply false` at the top-level. 
I think this was just purely due to the age of the project 🙂  I'll give this a try and see if that lets me set your plugin up correctly.

Thanks for the help!

**Comment by gmazzo** [comment]
I couldn't push to the sample project but here is as a diff what I meant about not applying the `kotlin` plugin to the root project:
```diff
60099a9 (HEAD -> main) Removing apply of `kotlin` plugin on the root (23 seconds ago) <guillermo.mazzola@glovoapp.com>

diff --git a/build.gradle b/build.gradle
index 0c61115..28173c1 100644
--- a/build.gradle
+++ b/build.gradle
@@ -18,11 +18,14 @@ buildscript {
 }
 
 plugins {
-    id 'org.jetbrains.kotlin.jvm' version '1.9.0'
+    id 'org.jetbrains.kotlin.jvm' version '1.9.0' apply false
+    id "io.github.gmazzo.test.aggregation.coverage" version "1.1.1"
     id "io.github.gmazzo.test.aggregation.results" version "1.1.1"
 }
 
-allprojects {
+subprojects {
+    apply plugin: 'org.jetbrains.kotlin.jvm'
+
     // Set the JVM language level for each module in the project
     kotlin {
         jvmToolchain {
```
