### ISSUE TITLE
don't force `enableUnitTestCoverage = true`

### ISSUE THREAD

**Issue by BugsBunnyBR** [gmazzo/gradle-android-test-aggregation-plugin#58]
Just check if that is true before adding that module to the report task, there are some modules that we just don't want to be part of it

**Comment by gmazzo** [comment]
The `android.buildTypes["debug"].enableUnitTestCoverage = true` is an opinionated design, in favor of a zero config setup and I think it cover the most usual use case for the plugin.

If, like your case, don't want some specific modules to be aggregated, you have two options:
1) Add `android.buildTypes["debug"].enableUnitTestCoverage = false` on those modules to prevent the coverage data from getting generated
2) Like described at [Filtering content
](https://github.com/gmazzo/gradle-android-test-aggregation-plugin#filtering-content) section, you can also use the exclude DSL in the root project:
```kotlin
testAggregation {
  modules {
    exclude(project("mylib"))
  }
}
```
