### ISSUE TITLE
Is there a way to see Aggregate report per module?

### ISSUE THREAD

**Issue by vramasam** [gmazzo/gradle-android-test-aggregation-plugin#61]
Hello @gmazzo ,

We tried out your plugin, it gives the aggregate report for entire project. We glad it worked seamlessly.

We also like to know is there a way to get the aggregate report for each module. If there is a way, can you please let me know how we can achieve that. Thank you in advance.

**Comment by gmazzo** [comment]
Hello there. Yes, `AGP` has a built-in `createDebugUnitTestCoverageReport` talk (when `enableUnitTestCoverage = true`) that will generate the report by module.
