### ISSUE TITLE
Is it possible to add/integrate violationRules with this plugin on final result (Code coverage verification)

### ISSUE THREAD

**Issue by vramasam** [gmazzo/gradle-android-test-aggregation-plugin#63]
Hello @gmazzo 

Is it possible to add/integrate violationRules with this plugin on final result?

Something like this 
violationRules {
            rule {
                limit {
                    minimum = 0
                }
            }
            rule {
                element = 'BUNDLE'
                limit {
                    counter = 'LINE'
                    value = 'COVEREDRATIO'
                    minimum = 0.33
                }
            }
        }

Thanks in Advance

**Comment by vramasam** [comment]
FYI, currently used this code to achieve  it. But please sure if there is any build in support is there

task codeCoverageVerification {
        doLast {
            def jacocoResultPath = "${project.buildDir}/reports/jacoco/jacocoAggregatedReport/html/index.html"
            def file = new File(jacocoResultPath)
            if (!file.exists()) {
                println("Code coverage file does not exist: ${jacocoResultPath}")
            } else {
                def content = file.text
                def matcher = content =~ /Total[^%]*>(\d?\d?\d?%)/
                if (matcher) {
                    def percentageString = matcher[0][1]
                    def percentage = percentageString.replaceAll('%', '').toInteger()
                    println "Percentage as Integer: $percentage"
                    if (percentage < expectedCodeCoverageResult) {
                        throw new GradleException("Build aborted: Required code coverage is $expectedCodeCoverageResult percentage, but result is : $percentage percentage")
                    }
                } else {
                    println "Code coverage reports are not generated properly"
                }
            }
        }
    }

**Comment by gmazzo** [comment]
Hi there. This feature will fall out of scope of this plugin, as it will be extension built upon the [JaCoCo Report Aggregation Plugin](https://docs.gradle.org/current/userguide/jacoco_report_aggregation_plugin.html)

Said that, I think instead of parsing the HTML, you should be using the XML version of it, usually located at `build/reports/jacoco/jacocoAggregatedReport/jacocoAggregatedReport.xml`

**Comment by gmazzo** [comment]
Hi @vramasam input on #72, I managed to include this by just introducing a new task and reusing all code from `JaCoCo plugin` ;)
