### ISSUE TITLE
Test result aggregation for specific build variant

### ISSUE THREAD

**Issue by akexorcist** [gmazzo/gradle-android-test-aggregation-plugin#67]
Currently, `testAggregatedReport` will run unit tests with all build variants, but I want to run only specific build variants. Can you provide more options in Gradle to support this requirement?

For example, as in your demo project, I want `testAggregatedReport` to execute the unit test for `stageDebug` or `debug`.

**Comment by gmazzo** [comment]
Hi there, thanks for reporting this.

The DSL mean for this use case was the one described at [aggregateTestCoverage](https://github.com/gmazzo/gradle-android-test-aggregation-plugin#the-aggregatetestcoverage-dsl-extension) in the `README.ME`.

But I totally forgot about it when I extended this plugin to support Test Results as well, it's added at #68

**Comment by gmazzo** [comment]
Released at `2.1.0`

**Comment by akexorcist** [comment]
Thank you so much
