### ISSUE TITLE
Property 'extendedProperties' is final

### ISSUE THREAD

**Issue by modsfabio** [gmazzo/gradle-android-test-aggregation-plugin#69]
Hi!

Since updating to 2.1.0 I can't sync my project anymore. I get the following error:

`java.lang.RuntimeException: java.lang.IllegalStateException: The value for property 'extendedProperties$plugin' is final and cannot be changed any further.`

This only seems to happen in combination with `androidx.baselineprofile`.

Note: The module which uses `androidx.baselineprofile` is not included in the `testAggregation{}` block

**Comment by gmazzo** [comment]
Released at `2.1.1`
