### ISSUE TITLE
Access to JacocoCoverageVerification via the Plugin DSL?

### ISSUE THREAD

**Issue by agherschon** [gmazzo/gradle-android-test-aggregation-plugin#72]
Hello,

I'd like first to thank whoever is part of this plugin, amazing work!

Now to the question: in the official documentation of Jacoco we can [set violation rules](https://docs.gradle.org/current/userguide/jacoco_plugin.html#ex-configuring-violation-rules), how do we set this up within this plugin?

Thanks in advance :pray:

**Comment by agherschon** [comment]
@gmazzo Wow, already ready in `2.2.0` ? 👏🏻👏🏻👏🏻  
When can we expect this version to hit the official plugin portal? 😊

**Comment by agherschon** [comment]
Also, could we get the configuration examples in the `README.md` written in the Gradle Kotlin DSL? 🙏🏻

**Comment by gmazzo** [comment]
> @gmazzo Wow, already ready in `2.2.0` ? 👏🏻👏🏻👏🏻 When can we expect this version to hit the official plugin portal? 😊

Yeah, just released it (the release flow failed yesterday and I didn't noted it).

> Also, could we get the configuration examples in the README.md written in the Gradle Kotlin DSL? 🙏🏻

You do have it at [[Enforcing aggregated code coverage metrics](https://github.com/gmazzo/gradle-android-test-aggregation-plugin#enforcing-aggregated-code-coverage-metrics)](https://github.com/gmazzo/gradle-android-test-aggregation-plugin#enforcing-aggregated-code-coverage-metrics) already.
The DSL is exactly the same as JaCoCo plugin, so any example you can find only can be applied here

**Comment by agherschon** [comment]
Thank you very much @gmazzo 💙
